// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRFd5LZRnvFdUg9hGcZAmENRetVpd1fwM',
    appId: '1:243858277288:web:7250bd463d982b48b8539d',
    messagingSenderId: '243858277288',
    projectId: 'authentication-5a9a9',
    authDomain: 'authentication-5a9a9.firebaseapp.com',
    storageBucket: 'authentication-5a9a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_BzF9vlwgdohCqm-ehDxqUclIb-mzU9I',
    appId: '1:243858277288:android:ac4c66565fb10d4ab8539d',
    messagingSenderId: '243858277288',
    projectId: 'authentication-5a9a9',
    storageBucket: 'authentication-5a9a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNpXa9e5fap_Crvk8Yi-sG2IKAdNFviao',
    appId: '1:243858277288:ios:f6255628a2b2c35eb8539d',
    messagingSenderId: '243858277288',
    projectId: 'authentication-5a9a9',
    storageBucket: 'authentication-5a9a9.appspot.com',
    iosClientId: '243858277288-1p0jr2oeaa2efanhbphj2spo3fviugg7.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNpXa9e5fap_Crvk8Yi-sG2IKAdNFviao',
    appId: '1:243858277288:ios:f6255628a2b2c35eb8539d',
    messagingSenderId: '243858277288',
    projectId: 'authentication-5a9a9',
    storageBucket: 'authentication-5a9a9.appspot.com',
    iosClientId: '243858277288-1p0jr2oeaa2efanhbphj2spo3fviugg7.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceV1',
  );
}
